name: MicroTowerDefenceGame
options:
  bundleIdPrefix: com.mertefesensoy
  xcodeVersion: "15.0"
  deploymentTarget:
    iOS: "16.0"

packages:
  MicroTDCore:
    path: MicroTDCore

targets:
  MicroTowerDefenceGame:
    type: application
    platform: iOS
    sources: 
      - path: MicroTowerDefenceGame
    dependencies:
      - package: MicroTDCore
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.mertefesensoy.MicroTowerDefenceGame
        INFOPLIST_KEY_UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        ENABLE_PREVIEWS: YES
