// ProgressionTypes.swift
// Core types for meta-progression (XP, Unlocks, Persistent State)

import Foundation

/// Persistent player profile
public struct ProgressionProfile: Codable, Equatable, Sendable {
    public var xp: Int
    public var level: Int
    public var unlocks: Set<String>
    
    public init(xp: Int = 0, level: Int = 1, unlocks: Set<String> = []) {
        self.xp = xp
        self.level = level
        self.unlocks = unlocks
    }
}

/// Summary of a completed run for progression calculation
public struct RunSummary: Codable, Equatable, Sendable {
    public let runSeed: UInt64
    public let wavesCleared: Int
    public let ticksSurvived: Int
    public let coinsEarned: Int
    public let enemiesDefeated: Int
    public let didWin: Bool
    public let relicIDsChosen: [String]
    
    public init(runSeed: UInt64, wavesCleared: Int, ticksSurvived: Int, coinsEarned: Int, enemiesDefeated: Int, didWin: Bool, relicIDsChosen: [String]) {
        self.runSeed = runSeed
        self.wavesCleared = wavesCleared
        self.ticksSurvived = ticksSurvived
        self.coinsEarned = coinsEarned
        self.enemiesDefeated = enemiesDefeated
        self.didWin = didWin
        self.relicIDsChosen = relicIDsChosen
    }
}

/// Events generated by progression updates
public enum ProgressionEvent: Equatable, Sendable {
    case xpGained(amount: Int)
    case leveledUp(from: Int, to: Int)
    case unlocked(id: String)
}

/// Rules for XP and Unlocks
public struct ProgressionRules: Sendable {
    public init() {}
    
    // XP Formula
    public func xpForRun(_ run: RunSummary) -> Int {
        var xp = 0
        xp += run.wavesCleared * 50
        xp += run.enemiesDefeated * 5
        xp += Int(Double(run.ticksSurvived) / 60.0) // 1 XP per second
        if run.didWin {
            xp += 500
        }
        return xp
    }
    
    // Leveling Curve
    public func xpRequiredForLevel(_ level: Int) -> Int {
        // Simple quadratic curve: 100 * level^2
        return 100 * level * level
    }
    
    // Unlocks Check
    public func unlocksForLevel(_ level: Int) -> [String] {
        switch level {
        case 2: return ["relic_uncommon_pack", "tower_sniper"]
        case 3: return ["relic_rare_pack", "tower_missile"]
        case 5: return ["relic_legendary_pack"]
        default: return []
        }
    }
}
